version: "3.9"

services:

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/webhook_db
      REDIS_HOST: redis
      REDIS_PORT: 6379

  worker:
    build: .
    command: npm run worker
    depends_on:
      - redis
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/webhook_db
      REDIS_HOST: redis
      REDIS_PORT: 6379

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webhook_db
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
